### ISSUE TITLE
Output git tag in `mach update` output

### ISSUE THREAD

**Issue by tleguijt** [mach-composer/mach-composer-cli#149]
If a certain commit is tagged, show the git tag next to the commit hash.
Ideally you'd want to work with tags in your component versioning.

Output could be something like;

```
Updates for my-component...
  1.1.0 (765b554): feat: update commercetools SDK
  6952faf: chore: formatting
```

**Comment by demeyerthom** [comment]
Sounds good! I will add it to the list!
