### ISSUE TITLE
Ability to use -lock=false

### ISSUE THREAD

**Issue by mikedingjan** [mach-composer/mach-composer-cli#301]
When running ``mach-composer plan`` within pull-requests it won't make any changes and in our use-case it's mainly for informational purpose.

It would be nice to provide a way where we can pass ``-lock=false`` to terraform when running a ``mach-composer plan`` in a pull-request, so that it won't interfere with a possible running deployment

**Comment by demeyerthom** [comment]
Fixed in https://github.com/mach-composer/mach-composer-cli/blob/main/CHANGELOG.md#v2130-2023-12-12
