### ISSUE TITLE
Improve component versioning

### ISSUE THREAD

**Issue by tleguijt** [mach-composer/mach-composer-cli#33]
Couple of challenges:

- It is now based on a commit hash. This makes it unclear if a change means a down- or upgrade
- From a MACH configuration perspective it's possible to define a component using a git tag. However, a artifact (serverless function ZIP file) needs to be present with both the commit hash and the git tag. This we should document better (and include in the cookiecutter)

**Comment by demeyerthom** [comment]
@tleguijt is this still something we should look into? In the current setup of mach composer I think we store all this metadata in the Mach Composer cloud (or infer it from a git checkout). 

Not sure if the problem still persists?

**Comment by tleguijt** [comment]
I think with https://github.com/mach-composer/mach-composer-cli/issues/149 covered we got it fixed.
MACH composer already allows you to use git tags (we have been using it for a long time on our project already) so I think with the `mach update` support we have everything to fully support it. Thanks!
