### ISSUE TITLE
The `subscription_id` should also be set on terraform backend for azure

### ISSUE THREAD

**Issue by mvantellingen** [mach-composer/mach-composer-cli#434]
We need to be able to set the subscription_id on the terraform state backend for azure when it should use a non-default

**Comment by demeyerthom** [comment]
@mvantellingen the azurem backend has a lot of potential options: https://developer.hashicorp.com/terraform/language/settings/backends/azurerm#configuration-variables

The ones that can be set in mach-composer are only the required ones for Managed Identity (MSI) authentication. However there are other options where `resource_group_name` is not required. 

I am thinking of removing resource_group_name as a required field, and instead adding the other options to the backend to be generated.

That, or still make resource_group_name not required and have the remainder be set through the environment variables, pretty much as we do with AWS and GCP. 

What are your thoughts on this?
