### ISSUE TITLE
Fatal error when unknown from-version is used with update check

### ISSUE THREAD

**Issue by tleguijt** [mach-composer/mach-composer-cli#435]
When performing `mach-composer update --check --cloud -f config.yaml` and a given from-version does not exist / is not known in MACH cloud, the CLI exits with `Error: undefined response type`.

When running with `MCC_DEBUG=1` I see that MACH cloud responds with a 500 error;

```
GET /organizations/.../projects/ecommerce/components/..../commits?from=9861b86&limit=200&offset=0&to=f47b3fb HTTP/1.1
Host: api.mach.cloud

----------------------------------------------------------------------
2024/08/28 20:39:42 DEBUG:
---[ RESPONSE ]-------------------------------------------------------
HTTP/2.0 500 Internal Server Error
```

**Suggestion**
This should be handler more gracefully. And in case of an unknown from-version it can always update to the latest. The only thing which is not possible in this case is to generate a changelog for that specific component

**Comment by demeyerthom** [comment]
Hmm strange. I think this might be an invalid response coming back from the new mach-composer-cloud api. I will check it out tomorrow to see what I can do to fix this and handle it gracefully

**Comment by demeyerthom** [comment]
Yeah this is happening in the underlying API. I am closing this ticket and opening a ticket there
