### ISSUE TITLE
Dry run option not doing anything with register-component-version command

### ISSUE THREAD

**Issue by tleguijt** [mach-composer/mach-composer-cli#436]
**Problem**
`mach-composer cloud register-component-version test-component --organization <org> --project <project> 1234 --dry-run` actually performs the command and applies it in MACH cloud, and doesn't do a dry run.

**Versions tested**
`v2.19.0`
`v2.17.1`

**Comment by demeyerthom** [comment]
Double-checked the code, and looks like dry-run is only used when we run it in auto-mode (`--auto`). Auto adds the commits to the version.  When it is not in auto-mode it will only create a new component version with version and branch. I will update that to log the same line we do in `--auto` (but without the commits it found)
